project:
  type: website
  output-dir: docs

website:
  title: "Aashish Gupta"
  reader-mode: true
  navbar:
    search: false
    right:
      - href: https://lekhajokha.github.io
        text: Home
      - href: https://lekhajokha.github.io/updates
        text: Updates
      - href: https://lekhajokha.github.io/blog/
        text: Notes
      - href: ag_cv_2024.pdf
        text: CV

      
      
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true

editor: visual

