project:
  type: website
  output-dir: docs

website:
  title: "Aashish Gupta"
  reader-mode: true
  navbar:
    search: false
    right:
      - href: https://lekhajokha.github.io
        text: Home
      - href: https://lekhajokha.github.io/blog/
        text: Blog
      - href: https://lekhajokha.github.io
        text: CV
      - text: News etc. 
        href: https://lekhajokha.github.io
      
      
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true

editor: visual

